-- Vision Therapy AI Platform - MySQL Schema
-- Optimized for Aiven Free MySQL

CREATE DATABASE IF NOT EXISTS vision_app_db;
USE vision_app_db;

-- 1. Doctors
CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    qualification VARCHAR(255),
    hospital VARCHAR(255),
    phone VARCHAR(20),
    created_at DATETIME,
    updated_at DATETIME
);

-- 2. Patients
CREATE TABLE IF NOT EXISTS patients (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    doctor_id BIGINT,
    condition_description TEXT,
    age INT,
    created_at DATETIME,
    updated_at DATETIME,
    FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE SET NULL
);

-- 3. Exercises
CREATE TABLE IF NOT EXISTS exercises (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100),
    duration INT, -- in seconds
    description TEXT,
    created_at DATETIME,
    updated_at DATETIME
);

-- 4. Exercise Results (Capturing AI Metric Tensors)
CREATE TABLE IF NOT EXISTS exercise_results (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT,
    exercise_id BIGINT,
    session_id VARCHAR(100),
    accuracy DOUBLE,
    focus_duration INT,
    movement_score DOUBLE,
    improvement_score DOUBLE, -- Generated by Python ML
    created_at DATETIME,
    updated_at DATETIME,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
);

-- 5. AI Recommendations
CREATE TABLE IF NOT EXISTS recommendations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT,
    doctor_id BIGINT,
    exercise_id BIGINT,
    notes TEXT,
    priority VARCHAR(50),
    created_at DATETIME,
    updated_at DATETIME,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
    FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
);

-- 6. Appointments (Virtual Meetings)
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT,
    doctor_id BIGINT,
    appointment_time DATETIME NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING',
    meeting_url VARCHAR(255),
    notes TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE
);

-- 7. Clinical Chat Messages
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    sender_role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    timestamp DATETIME NOT NULL,
    is_read BOOLEAN DEFAULT FALSE
);
