spring.application.name=vision-app-backend
spring.datasource.url=jdbc:mysql://localhost:3306/vision_app_db
spring.datasource.username=root
spring.datasource.password=Angel@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Expose strict validation exception traces to React Axios interceptors
server.error.include-message=always