spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/vision_app_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Angel@123}

# AI Microservice URL (FastAPI)
ai.service.url=${AI_SERVICE_URL:http://localhost:5000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Expose strict validation exception traces to React Axios interceptors
server.error.include-message=always